name: Development CD

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  test-dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn
      
      - name: Build application
        run: yarn build

      - name: Lint the code
        run: yarn lint

      - name: Run test runner
        run: yarn test --passWithNoTests

  deploy-dev: 
    runs-on: ubuntu-latest

    needs: test-dev

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.DOKKU_HOST }}
          app-name: ${{ secrets.DOKKU_DEV_APP_NAME }}
          git-push-flags: --force
     