name: Tests

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop, master ]

  workflow_dispatch:

jobs:
  test-dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Lint the code
        run: yarn lint

      - name: Run test runner
        run: yarn test --passWithNoTests
      
      - name: Build application
        run: yarn build